"""init schema

Revision ID: 488c75bf3411
Revises: 
Create Date: 2026-05-03 21:23:34.398271
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '488c75bf3411'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('policies',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('version', sa.String(length=50), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('effective_from', sa.Date(), nullable=True),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policies'))
    )
    op.create_table('sellers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('sla_level', sa.String(length=50), nullable=True),
    sa.Column('rating', sa.Numeric(precision=3, scale=2), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sellers'))
    )
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('customers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('tier', sa.String(length=50), nullable=False),
    sa.Column('preferred_language', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_customers_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers'))
    )
    op.create_table('policy_chunks',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('policy_id', sa.String(length=36), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=True),
    sa.Column('chunk_text', sa.Text(), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_policy_chunks_policy_id_policies')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_policy_chunks'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('channel', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('latest_intent', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_conversations_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('orders',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('seller_id', sa.String(length=36), nullable=False),
    sa.Column('order_status', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=50), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('promised_delivery_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_orders_customer_id_customers')),
    sa.ForeignKeyConstraint(['seller_id'], ['sellers.id'], name=op.f('fk_orders_seller_id_sellers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('agent_traces',
    sa.Column('id', sa.String(length=100), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('workflow_name', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('requires_human_approval', sa.Boolean(), nullable=False),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('state_snapshot', sa.JSON(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_agent_traces_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_agent_traces'))
    )
    op.create_table('cases',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('case_type', sa.String(length=50), nullable=True),
    sa.Column('priority', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ai_summary', sa.Text(), nullable=True),
    sa.Column('assigned_role', sa.String(length=50), nullable=True),
    sa.Column('assigned_user_id', sa.String(length=36), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['assigned_user_id'], ['users.id'], name=op.f('fk_cases_assigned_user_id_users')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_cases_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_cases_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_cases'))
    )
    op.create_table('messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=False),
    sa.Column('sender_type', sa.String(length=50), nullable=False),
    sa.Column('sender_id', sa.String(length=100), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('order_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=100), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_items_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_items'))
    )
    op.create_table('shipments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('carrier', sa.String(length=100), nullable=True),
    sa.Column('tracking_no', sa.String(length=100), nullable=True),
    sa.Column('shipment_status', sa.String(length=50), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('last_update', sa.DateTime(), nullable=True),
    sa.Column('delay_risk_score', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_shipments_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipments')),
    sa.UniqueConstraint('tracking_no', name=op.f('uq_shipments_tracking_no'))
    )
    op.create_table('approvals',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=False),
    sa.Column('approval_type', sa.String(length=50), nullable=False),
    sa.Column('requested_action', sa.Text(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('risk_level', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('ai_reason', sa.Text(), nullable=True),
    sa.Column('policy_citation', sa.JSON(), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_approvals_case_id_cases')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('fk_approvals_reviewer_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvals'))
    )
    op.create_table('proactive_alerts',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=True),
    sa.Column('shipment_id', sa.String(length=36), nullable=True),
    sa.Column('alert_type', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('message_draft', sa.Text(), nullable=True),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_proactive_alerts_case_id_cases')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_proactive_alerts_order_id_orders')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_proactive_alerts_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_proactive_alerts'))
    )
    op.create_table('refund_requests',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('requested_resolution', sa.String(length=50), nullable=True),
    sa.Column('eligibility_status', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=False),
    sa.Column('ai_recommendation', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_refund_requests_case_id_cases')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_refund_requests_customer_id_customers')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_refund_requests_order_id_orders')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refund_requests'))
    )
    op.create_table('shipment_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=True),
    sa.Column('event_message', sa.String(length=255), nullable=True),
    sa.Column('location', sa.String(length=255), nullable=True),
    sa.Column('event_time', sa.DateTime(), nullable=True),
    sa.Column('raw_payload', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_events_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_events'))
    )
    op.create_table('shipment_items',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('shipment_id', sa.String(length=36), nullable=False),
    sa.Column('order_item_id', sa.String(length=36), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['order_item_id'], ['order_items.id'], name=op.f('fk_shipment_items_order_item_id_order_items')),
    sa.ForeignKeyConstraint(['shipment_id'], ['shipments.id'], name=op.f('fk_shipment_items_shipment_id_shipments')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_shipment_items'))
    )
    op.create_table('tool_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=False),
    sa.Column('agent_name', sa.String(length=100), nullable=True),
    sa.Column('tool_name', sa.String(length=100), nullable=True),
    sa.Column('input_payload', sa.JSON(), nullable=True),
    sa.Column('output_payload', sa.JSON(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.id'], name=op.f('fk_tool_logs_trace_id_agent_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tool_logs'))
    )
    op.create_table('attachments',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('owner_type', sa.String(length=50), nullable=False),
    sa.Column('message_id', sa.String(length=36), nullable=True),
    sa.Column('case_id', sa.String(length=50), nullable=True),
    sa.Column('refund_request_id', sa.String(length=50), nullable=True),
    sa.Column('policy_id', sa.String(length=36), nullable=True),
    sa.Column('attachment_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_group', sa.String(length=50), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('bucket_name', sa.String(length=100), nullable=False),
    sa.Column('object_key', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_size_bytes', sa.Integer(), nullable=True),
    sa.Column('uploaded_by_type', sa.String(length=50), nullable=True),
    sa.Column('uploaded_by_customer_id', sa.String(length=36), nullable=True),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('upload_status', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], name=op.f('fk_attachments_case_id_cases')),
    sa.ForeignKeyConstraint(['message_id'], ['messages.id'], name=op.f('fk_attachments_message_id_messages')),
    sa.ForeignKeyConstraint(['policy_id'], ['policies.id'], name=op.f('fk_attachments_policy_id_policies')),
    sa.ForeignKeyConstraint(['refund_request_id'], ['refund_requests.id'], name=op.f('fk_attachments_refund_request_id_refund_requests')),
    sa.ForeignKeyConstraint(['uploaded_by_customer_id'], ['customers.id'], name=op.f('fk_attachments_uploaded_by_customer_id_customers')),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('attachments')
    op.drop_table('tool_logs')
    op.drop_table('shipment_items')
    op.drop_table('shipment_events')
    op.drop_table('refund_requests')
    op.drop_table('proactive_alerts')
    op.drop_table('approvals')
    op.drop_table('shipments')
    op.drop_table('order_items')
    op.drop_table('messages')
    op.drop_table('cases')
    op.drop_table('agent_traces')
    op.drop_table('orders')
    op.drop_table('conversations')
    op.drop_table('policy_chunks')
    op.drop_table('customers')
    op.drop_table('users')
    op.drop_table('sellers')
    op.drop_table('policies')
    # ### end Alembic commands ###
