"""add admin notes fields

Revision ID: 4b5bb6c546ab
Revises: 488c75bf3411
Create Date: 2026-05-03 21:36:17.535745
"""
from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = '4b5bb6c546ab'
down_revision = '488c75bf3411'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('approvals', sa.Column('review_note', sa.Text(), nullable=True))
    op.add_column('cases', sa.Column('resolution_note', sa.Text(), nullable=True))
    op.add_column('proactive_alerts', sa.Column('resolution_note', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('proactive_alerts', 'resolution_note')
    op.drop_column('cases', 'resolution_note')
    op.drop_column('approvals', 'review_note')
    # ### end Alembic commands ###
