"""add_memory_tables_and_shopify_columns

Revision ID: 59617f241933
Revises: d9f1a2b3c4e5
Create Date: 2026-05-11 09:17:42.250722
"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


# revision identifiers, used by Alembic.
revision = '59617f241933'
down_revision = 'd9f1a2b3c4e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_episodic_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_episodic_memory_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_episodic_memory'))
    )
    op.create_index(op.f('ix_customer_episodic_memory_customer_id'), 'customer_episodic_memory', ['customer_id'], unique=False)
    op.create_table('customer_long_term_memory',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('memory_type', sa.String(length=50), nullable=True),
    sa.Column('key', sa.String(length=100), nullable=True),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('source_agent', sa.String(length=50), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_long_term_memory_customer_id_customers'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_long_term_memory'))
    )
    op.create_index(op.f('ix_customer_long_term_memory_customer_id'), 'customer_long_term_memory', ['customer_id'], unique=False)
    op.create_index(op.f('ix_customer_long_term_memory_key'), 'customer_long_term_memory', ['key'], unique=False)
    op.create_table('execution_plans',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('trace_id', sa.String(length=100), nullable=True),
    sa.Column('intent', sa.String(length=100), nullable=True),
    sa.Column('plan_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('replan_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['trace_id'], ['agent_traces.id'], name=op.f('fk_execution_plans_trace_id_agent_traces')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_plans'))
    )
    op.add_column('orders', sa.Column('shopify_order_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(op.f('uq_orders_shopify_order_id'), 'orders', ['shopify_order_id'])
    op.add_column('shipments', sa.Column('shopify_fulfillment_id', sa.String(length=100), nullable=True))
    op.create_unique_constraint(op.f('uq_shipments_shopify_fulfillment_id'), 'shipments', ['shopify_fulfillment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uq_shipments_shopify_fulfillment_id'), 'shipments', type_='unique')
    op.drop_column('shipments', 'shopify_fulfillment_id')
    op.drop_constraint(op.f('uq_orders_shopify_order_id'), 'orders', type_='unique')
    op.drop_column('orders', 'shopify_order_id')
    op.drop_table('execution_plans')
    op.drop_index(op.f('ix_customer_long_term_memory_key'), table_name='customer_long_term_memory')
    op.drop_index(op.f('ix_customer_long_term_memory_customer_id'), table_name='customer_long_term_memory')
    op.drop_table('customer_long_term_memory')
    op.drop_index(op.f('ix_customer_episodic_memory_customer_id'), table_name='customer_episodic_memory')
    op.drop_table('customer_episodic_memory')
    # ### end Alembic commands ###
