from datetime import datetime


def get_workflow_02_seed_data() -> dict[str, list[dict]]:
    now = datetime.utcnow()

    return {
        "conversations": [
            {
                "id": "CONV-002",
                "customer_id": "CUST-001",
                "channel": "web_chat",
                "status": "open",
                "latest_intent": "refund_request",
                "created_at": now,
                "updated_at": now,
            }
        ],
        "messages": [
            {
                "id": "MSG-002",
                "conversation_id": "CONV-002",
                "sender_type": "customer",
                "sender_id": "CUST-001",
                "content": "สินค้าเสียหาย ขอคืนเงิน",
                "metadata_json": {"language": "th"},
                "created_at": now,
            }
        ],
        "cases": [
            {
                "id": "CS-5521",
                "customer_id": "CUST-001",
                "order_id": "SP-1024",
                "case_type": "refund",
                "priority": "medium",
                "status": "open",
                "ai_summary": "Customer reported damaged item and asked for refund.",
                "assigned_role": "admin",
                "assigned_user_id": None,
                "created_by": "ai",
                "created_at": now,
                "updated_at": now,
            }
        ],
        "refund_requests": [
            {
                "id": "RF-5521",
                "order_id": "SP-1024",
                "customer_id": "CUST-001",
                "case_id": "CS-5521",
                "reason": "Damaged item",
                "requested_resolution": "refund",
                "eligibility_status": "under_review",
                "risk_score": 45,
                "ai_recommendation": "Evidence is present and can proceed to review.",
                "status": "pending",
                "created_at": now,
                "updated_at": now,
            }
        ],
        "attachments": [
            {
                "id": "ATT-001",
                "owner_type": "refund_request",
                "message_id": None,
                "case_id": "CS-5521",
                "refund_request_id": "RF-5521",
                "policy_id": None,
                "attachment_type": "image",
                "evidence_group": "damaged_item",
                "display_order": 1,
                "description": "Damaged item photo",
                "bucket_name": "evidence",
                "object_key": "refund_request/RF-5521/damaged_item/01_front-crack.jpg",
                "file_name": "01_front-crack.jpg",
                "mime_type": "image/jpeg",
                "file_size_bytes": 120034,
                "uploaded_by_type": "customer",
                "uploaded_by_customer_id": "CUST-001",
                "uploaded_by_user_id": None,
                "upload_status": "uploaded",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "ATT-002",
                "owner_type": "refund_request",
                "message_id": None,
                "case_id": "CS-5521",
                "refund_request_id": "RF-5521",
                "policy_id": None,
                "attachment_type": "image",
                "evidence_group": "parcel_package",
                "display_order": 2,
                "description": "Package photo",
                "bucket_name": "evidence",
                "object_key": "refund_request/RF-5521/parcel_package/02_box-damaged.jpg",
                "file_name": "02_box-damaged.jpg",
                "mime_type": "image/jpeg",
                "file_size_bytes": 110210,
                "uploaded_by_type": "customer",
                "uploaded_by_customer_id": "CUST-001",
                "uploaded_by_user_id": None,
                "upload_status": "uploaded",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "ATT-003",
                "owner_type": "refund_request",
                "message_id": None,
                "case_id": "CS-5521",
                "refund_request_id": "RF-5521",
                "policy_id": None,
                "attachment_type": "image",
                "evidence_group": "parcel_label",
                "display_order": 3,
                "description": "Shipping label photo",
                "bucket_name": "evidence",
                "object_key": "refund_request/RF-5521/parcel_label/03_shipping-label.jpg",
                "file_name": "03_shipping-label.jpg",
                "mime_type": "image/jpeg",
                "file_size_bytes": 90344,
                "uploaded_by_type": "customer",
                "uploaded_by_customer_id": "CUST-001",
                "uploaded_by_user_id": None,
                "upload_status": "uploaded",
                "created_at": now,
                "updated_at": now,
            },
        ],
        "policies": [
            {
                "id": "POL-001",
                "title": "Refund Policy",
                "category": "refund",
                "version": "v1.0",
                "content": "Damaged items can be refunded when the customer provides photo evidence within the review window.",
                "status": "active",
                "effective_from": None,
                "effective_to": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "POL-002",
                "title": "Return Policy",
                "category": "return",
                "version": "v1.0",
                "content": "Customers can request a return when the item is defective or incorrect.",
                "status": "active",
                "effective_from": None,
                "effective_to": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "POL-003",
                "title": "Compensation Policy",
                "category": "compensation",
                "version": "v1.0",
                "content": "High-risk refunds may require human approval before compensation is issued.",
                "status": "active",
                "effective_from": None,
                "effective_to": None,
                "created_at": now,
                "updated_at": now,
            },
        ],
        "policy_chunks": [
            {
                "id": "PCH-001",
                "policy_id": "POL-001",
                "chunk_index": 0,
                "chunk_text": "Damaged items can be refunded with customer photo evidence.",
                "metadata_json": {"section": "1.1"},
                "embedding_id": "emb-pol-001-0",
                "created_at": now,
            },
            {
                "id": "PCH-002",
                "policy_id": "POL-002",
                "chunk_index": 0,
                "chunk_text": "Returns are allowed for defective products.",
                "metadata_json": {"section": "2.1"},
                "embedding_id": "emb-pol-002-0",
                "created_at": now,
            },
            {
                "id": "PCH-003",
                "policy_id": "POL-003",
                "chunk_index": 0,
                "chunk_text": "Escalate high-risk compensation for manual approval.",
                "metadata_json": {"section": "3.1"},
                "embedding_id": "emb-pol-003-0",
                "created_at": now,
            },
        ],
        "approvals": [
            {
                "id": "APR-1001",
                "case_id": "CS-5521",
                "approval_type": "refund",
                "requested_action": "Review refund recommendation",
                "amount": 2490.00,
                "currency": "THB",
                "risk_level": "medium",
                "status": "pending",
                "ai_reason": "Refund request queued for manual review.",
                "policy_citation": {"policy_ids": ["POL-001", "POL-003"]},
                "reviewer_id": None,
                "reviewed_at": None,
                "created_at": now,
            }
        ],
    }
