from datetime import datetime


def get_workflow_01_seed_data() -> dict[str, list[dict]]:
    now = datetime.utcnow()

    return {
        "users": [
            {
                "id": "U-001",
                "name": "customer_demo",
                "email": "customer_demo@shopeasy.local",
                "role": "customer",
                "status": "active",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "U-002",
                "name": "admin_demo",
                "email": "admin_demo@shopeasy.local",
                "role": "admin",
                "status": "active",
                "created_at": now,
                "updated_at": now,
            },
        ],
        "customers": [
            {
                "id": "CUST-001",
                "user_id": "U-001",
                "name": "Narisara",
                "email": "narisara@example.com",
                "phone": "0800000000",
                "tier": "normal",
                "preferred_language": "th",
                "created_at": now,
                "updated_at": now,
            }
        ],
        "sellers": [
            {
                "id": "SELL-001",
                "name": "FashionHub",
                "sla_level": "standard",
                "rating": 4.8,
                "status": "active",
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "SELL-002",
                "name": "GadgetMall",
                "sla_level": "priority",
                "rating": 4.6,
                "status": "active",
                "created_at": now,
                "updated_at": now,
            },
        ],
        "orders": [
            {
                "id": "SP-1024",
                "customer_id": "CUST-001",
                "seller_id": "SELL-001",
                "order_status": "shipped",
                "payment_status": "paid",
                "total_amount": 2490.00,
                "currency": "THB",
                "promised_delivery_date": None,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "SP-2044",
                "customer_id": "CUST-001",
                "seller_id": "SELL-002",
                "order_status": "shipped",
                "payment_status": "paid",
                "total_amount": 1790.00,
                "currency": "THB",
                "promised_delivery_date": None,
                "created_at": now,
                "updated_at": now,
            },
        ],
        "order_items": [
            {
                "id": "ITEM-1001",
                "order_id": "SP-1024",
                "product_name": "เสื้อ",
                "sku": "FHB-SHIRT-01",
                "quantity": 1,
                "unit_price": 590.00,
                "created_at": now,
            },
            {
                "id": "ITEM-1002",
                "order_id": "SP-1024",
                "product_name": "สูท",
                "sku": "FHB-SUIT-01",
                "quantity": 1,
                "unit_price": 1290.00,
                "created_at": now,
            },
            {
                "id": "ITEM-1003",
                "order_id": "SP-1024",
                "product_name": "กางเกง",
                "sku": "FHB-PANTS-01",
                "quantity": 1,
                "unit_price": 610.00,
                "created_at": now,
            },
            {
                "id": "ITEM-2001",
                "order_id": "SP-2044",
                "product_name": "หูฟัง",
                "sku": "GDM-HP-01",
                "quantity": 1,
                "unit_price": 1790.00,
                "created_at": now,
            },
        ],
        "shipments": [
            {
                "id": "SHP-9001",
                "order_id": "SP-1024",
                "carrier": "Flash Express",
                "tracking_no": "TH9001",
                "shipment_status": "delivered",
                "eta": None,
                "last_update": now,
                "delay_risk_score": 0,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "SHP-9002",
                "order_id": "SP-1024",
                "carrier": "Flash Express",
                "tracking_no": "TH9002",
                "shipment_status": "in_transit",
                "eta": None,
                "last_update": now,
                "delay_risk_score": 87,
                "created_at": now,
                "updated_at": now,
            },
            {
                "id": "SHP-9003",
                "order_id": "SP-2044",
                "carrier": "Kerry",
                "tracking_no": "TH9003",
                "shipment_status": "out_for_delivery",
                "eta": None,
                "last_update": now,
                "delay_risk_score": 10,
                "created_at": now,
                "updated_at": now,
            },
        ],
        "shipment_items": [
            {
                "id": "SHIPITEM-001",
                "shipment_id": "SHP-9001",
                "order_item_id": "ITEM-1001",
                "quantity": 1,
                "created_at": now,
            },
            {
                "id": "SHIPITEM-002",
                "shipment_id": "SHP-9001",
                "order_item_id": "ITEM-1002",
                "quantity": 1,
                "created_at": now,
            },
            {
                "id": "SHIPITEM-003",
                "shipment_id": "SHP-9002",
                "order_item_id": "ITEM-1003",
                "quantity": 1,
                "created_at": now,
            },
            {
                "id": "SHIPITEM-004",
                "shipment_id": "SHP-9003",
                "order_item_id": "ITEM-2001",
                "quantity": 1,
                "created_at": now,
            },
        ],
        "conversations": [
            {
                "id": "CONV-001",
                "customer_id": "CUST-001",
                "channel": "web_chat",
                "status": "open",
                "latest_intent": "track_shipment",
                "created_at": now,
                "updated_at": now,
            }
        ],
        "messages": [
            {
                "id": "MSG-001",
                "conversation_id": "CONV-001",
                "sender_type": "customer",
                "sender_id": "CUST-001",
                "content": "ของฉันอยู่ไหนแล้ว",
                "metadata_json": {"language": "th"},
                "created_at": now,
            }
        ],
        "agent_traces": [
            {
                "id": "TRACE-001",
                "conversation_id": "CONV-001",
                "case_id": None,
                "workflow_name": "workflow_01_track_shipment",
                "intent": "track_shipment",
                "confidence": 0.982,
                "status": "completed",
                "requires_human_approval": False,
                "final_response": "Tracking summary generated.",
                "state_snapshot": {"active_shipment_ids": ["SHP-9002", "SHP-9003"]},
                "started_at": now,
                "ended_at": now,
            }
        ],
        "tool_logs": [
            {
                "id": "LOG-001",
                "trace_id": "TRACE-001",
                "agent_name": "router_node",
                "tool_name": "detect_intent",
                "input_payload": {"message": "ของฉันอยู่ไหนแล้ว"},
                "output_payload": {"intent": "track_shipment"},
                "status": "success",
                "latency_ms": 32,
                "error_message": None,
                "created_at": now,
            },
            {
                "id": "LOG-002",
                "trace_id": "TRACE-001",
                "agent_name": "shipping_node",
                "tool_name": "get_shipments_by_order",
                "input_payload": {"order_ids": ["SP-1024", "SP-2044"]},
                "output_payload": {"shipment_ids": ["SHP-9002", "SHP-9003"]},
                "status": "success",
                "latency_ms": 54,
                "error_message": None,
                "created_at": now,
            },
        ],
    }
